apiVersion: v1
kind: Service
metadata:
  labels:
    app: cve-agent
  name: cve-agent
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: cve-agent
